# local_private_key: "0x96ae6a02fe9685dc45e20d4f04390d7fdaba405137bb44b97a2db46330d80dbc"
# enrs:
#   - enr:-IW4QGSCA9OZjOk14p2uDXDABw_GyCcc2ko6Z9PrkS66sJ23E65smTb08GrS_yJ1ipN8OpExDY1zAlHpz9D4ZSnrbAEBgmlkgnY0gmlwhH8AAAGJc2VjcDI1NmsxoQPoUBRAhF9QakPlj7ZK_5lqEHC_jZJ3kEWZ4iUIPIg254N1ZHCDBipI  # Alice, current
#   - enr:-IW4QI21ZNk9LThfR8suvr4sr05Job0HaAucpp-XpYaA2NNoYRkJi2DdFZ4i5VBW7axPK7MVg63zxw_qm4TClAXogLYBgmlkgnY0gmlwhH8AAAGJc2VjcDI1NmsxoQOpw6TAKiZq1HaZdL-MBJgGJ6L9V7ntwzk5JbTJ8luwf4N1ZHCDBipJ  # Bob, current

# routing_table:
#   - "0xd5ae289621a449e9a1d1611dee733454ffa71340e81da0727e064ad370207ec0"  # Bob
# host: "127.0.0.1"
# port: 40404
local_private_key: "0x783b2d2423e1d731fdfa32cb77a01ade8a5ddcd060661035e917d91155fac105"
enrs:
  - enr:-Im4QE1PcCm13jYPXUiAAU2bawNweMPRoL8gC_7_RJPKurfYPTDGOUkqG8-aOQMs_J-9JX60WD4GZr-LIRp6hGjLfCMBg2V0aDKCaWSCdjSCaXCEfwAAAYlzZWNwMjU2azGhAqRZx4gTvOjmDg-M95NPAafQxjECPKmk9QVwFpae1mpLg3VkcIIwnA
  - enr:-Im4QKDN8yi-iAkPK4TJGdDvMnblJMGJJMMirZLb1uTo0oG9DYVCV3v8gXWpLd95PkIF-CMVQFuDogX5gaPvcWWD79IBg2V0aDOCaWSCdjSCaXCEfwAAAYlzZWNwMjU2azGhAhLKKP7-GnyrzgpbQ4GncwIb6ACzSSit-K2eJa98i32ig3VkcIIxeg
routing_table:
  - "0xe88e2f03f291d6b5ff7755c263da3d19a04b42a342dee0142b82aa405263c7bc"  # Bob
host: "127.0.0.1"
port: 12444
