local_private_key: "0x5daea82e1428e6d6c0aa6253ff1ff235ebc12ceb7bebae5e033e79c7975365dc"
enrs:
  - enr:-Im4QKDN8yi-iAkPK4TJGdDvMnblJMGJJMMirZLb1uTo0oG9DYVCV3v8gXWpLd95PkIF-CMVQFuDogX5gaPvcWWD79IBg2V0aDOCaWSCdjSCaXCEfwAAAYlzZWNwMjU2azGhAhLKKP7-GnyrzgpbQ4GncwIb6ACzSSit-K2eJa98i32ig3VkcIIxeg
  - enr:-Im4QE1PcCm13jYPXUiAAU2bawNweMPRoL8gC_7_RJPKurfYPTDGOUkqG8-aOQMs_J-9JX60WD4GZr-LIRp6hGjLfCMBg2V0aDKCaWSCdjSCaXCEfwAAAYlzZWNwMjU2azGhAqRZx4gTvOjmDg-M95NPAafQxjECPKmk9QVwFpae1mpLg3VkcIIwnA
routing_table:
  - "0xbf17806bd74acf885c6ca332dfe213cd46c2b2dbe0f70e5ac63b9ff021df2407"
host: "127.0.0.1"
port: 12666
